### PR TITLE
Libpdfium build 2 files found (pickFirst)

### PR DESCRIPTION
**Pull request by HeropolisDa2ny**
Temp fix for the building bug of 2 files found for libpdfium.so

### CODE REVIEW

**Comment by sommen01** [comment]
It works for me

**Comment by HeropolisDa2ny** [comment]
@espresso3389 are you fine to approve this PR or you would prefer to look for another solution ?

**Comment by espresso3389** [comment]
As I descibed on https://github.com/espresso3389/pdfrx/issues/8#issuecomment-2205139356, this change is just a workaround and sometimes it gets very harmful. We need more discussion on it on #8 before accepting such PRs.

**Comment by espresso3389** [comment]
After several hours of investigation, I finally decided to merge this anyway. There might be several side effects but the possibilities are so small. The risk can be acceptable.

**Pull request merged**
