### PR TITLE
Add Document rotation

### PR DESCRIPTION
**Pull request by wenchen**
I added a rotation parameter to the current code to rotate the page. When the page is rotated, the document is reloaded to draw the screen again. This ensures that the correct document size is displayed after the page is rotated.

### CODE REVIEW

**Comment by espresso3389** [comment]
Please understand the code structure and please keep such UI related code change on widget codes only.

**Comment by espresso3389** [comment]
By the way, why the rotation is document level parameter?
For what purpose do you want to do such thing?

**Comment by espresso3389** [comment]
Another head-ache with the page rotation is text selection (#4) that I've been working on...

**Comment by wenchen** [comment]
I tried several methods of page rotation, but it wasn't until I saw the demo page provided by pdf.js that I realized that it rotated the entire document after rotation. After some investigation, I found that I had to tell it the current rotation angle when adding a page. The PDFium test also seems to be the same. I think it should be possible to rotate a part of the page. I will look into how to handle it better. Thank you for your reply.

**Comment by espresso3389** [comment]
Page rotation may be easily implemented on widget side.

So, in my opinion, such rotation can be done within PdfViewer widget. No lower layer should handle such UI side thing.

If I implement the rotation, I will do:

- Add document level (or page level) rotation angle in PdfViewerParams
- Update layout logic in _PdfViewerState._layoutPages
- Update drawing logic in _PdfViewerState._customPaint

**Pull request closed without merging**
